[tox]
envlist = py36, py37, py38, py39, py310, py311
skipsdist = True

[testenv]
deps =
    -r requirements-dev.txt
commands =
    pytest tests/ -v --cov=consultor_cnpj --cov-report=term
    flake8 consultor_cnpj tests
    mypy consultor_cnpj